require: rubocop-rspec

AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.0

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/step_definitions/**/*'

RSpec/MessageSpies:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
