require: rubocop-rspec

AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.0

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 20

BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/step_definitions/**/*'

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
